config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#welcome'
  resources :contact, only: [:new, :create]
  resources :posts
  get 'about', to: 'pages#about'
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :create, :validate => true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "portfoliozag@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
      if @contact.deliver
        flash[:notice] = "Successfully sent email!"
        redirect_to root_path
      else
        flash.now[:alert] = "Can not send Message!"
        render 'new'
      end
  end

  def message

  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_contact_form.html.erb
<% if user_signed_in? %>
<div class="contact-form">
<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.hidden_field :email, value: current_user.email %>
    </div>
    <div class="form-group">
    <%= f.label :create %><br>
    <%= f.text_area :create, rows: 8, cols: 40, required: true, class: "contact-form-text-area form-control",
                    placeholder: "Send me a create"%><br>
    </div>
    <%= f.submit 'Send Message', class: 'btn btn-primary btn-lg btn-block' %>

<% end %>
</div>
<% end %>

app/views/contact/index.html.erb
<% if user_signed_in?  %>
<div id="contact">
  <%= render 'contact_form' %>
</div>
<% else %>
  <div class="sign-up">
<h1 class="sign-up-txt">Sign up to contact me</h1>
<%= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary btn-lg btn-block"  %>
  </div>
<% end %>

app/views/contact/new.html.erb
<% if user_signed_in?  %>
  <h1>Say Hello!</h1>
<div id="contact">
  <%= render 'contact_form' %>
</div>
<% else %>
  <div class="sign-up">
<h1 class="sign-up-txt">Sign up to contact me</h1>
<%= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary btn-lg btn-block"  %>
  </div>
<% end %>