config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#welcome'
  resources :contact, only: [:new, :create]
  resources :posts
  get 'about', to: 'pages#about'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :create, :validate => true

  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "portfoliozag@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, length: { maximum: 100 }
  validates :body, presence: true, length: { maximum: 500 }
  validates :image, content_type: {in: %w[image/jpeg image/gif image/png],
                                   create: "must be a valid image format"},
            size: {less_than: 5.megabytes, create: "should be less tha 5MB"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource)
    root_path
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
      if @contact.deliver
        flash[:notice] = "Successfully sent email!"
        redirect_to root_path
      else
        flash.now[:alert] = "Can not send Message!"
        render 'new'
      end
  end

  def message

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to root_path
    else
      flash.now[:alert] = "Post failed to be created!"
      render 'new'
    end
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post is Updated"
    else
      flash[:alert] = 'Post is not updated'
    end
  end
  def edit
  end
  def destroy
    @post = Post.find(params[:id])
    if @post.present?
      @post.destroy
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:name, :body, :image)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    # custom sign-in code
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "WELCOME", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'ABOUT', about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to "CONTACT", new_contact_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <% if user_signed_in? %>
            <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          <% else %>
            <%= link_to "LOG IN", new_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="about align-items-center">
  <div  class="d-flex align-items-center flex-column about-container ">
  <div class="about-text">
    <h3 class="about-title">
      Danilo Zagarcanin
      </h3>
    <h3 class="about-title">
      Full-Stack Developer
    </h3>
    <p class="about-par">
      <strong>SKILLS:</strong>
      JavaScript (ES5/ES6), Ruby, HTML, CSS, Ruby on Rails, React, jQuery, Bootstrap, SQL, RSpec, Git, GitHub, Webpack, Heroku
    </p>
    <p class="about-par">
      <strong>RELEVANT EXPERIENCE:</strong>
      Microverse Student			        	 March 2019- Present
      Microverse, Remote
      Completed 300+  coding challenges on LeetCode, Hackerrank, Replit, Code Wars.
      Finished 30+  projects as part of the Microverse curriculum.
      Currently over 5+ published articles about web development.
      Published articles on HackerNoon, Medium and i wrote articles for Non-governmental
      organization that offers free courses for those who seek to become graphic designers
      and web developers.
      Freelance Full-Stack Developer				                January 2017 - February 2019
    </p>
    <p class="about-par">
      <strong>EDUCATION:</strong>

      Microverse, Certificate						      November 2018 - September 2019
      I spent 1100+ hours mastering algorithms, data structures, and full-stack development
      while simultaneously developing projects in Ruby, Rails, Javascript, React, and Redux.
      Developed skills in remote pair-programming, using Github, industry-standard git flows,
      and daily standups to communicate and collaborate with international remote developers.
      Student  at Computer Science University of Montenegro
    </p>
  </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<main class="welcome container-fluid ">
  <div class="welcome-content d-flex justify-content-center ">
      <div class="media">
        <%= image_tag('mer.jpg', class: "me align-self-center mr-3") %>
        <div class="media-body mt-5">
          <h1 class="media-text">Hi there!
            My name is Danilo Zagarčanin<br>
            and I am a Web Developer.</h1>
          <%= link_to "View my work", posts_path, class: "welcome-btn" %>
        </div>
      </div>
  </div>
  </div>
</main>
<!-- Footer -->